export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const ADD_TO_FAVORITES_START = 'ADD_TO_FAVORITES_START';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES_START = 'REMOVE_FROM_FAVORITES_START';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';


export const DELETE_VACATION = 'DELETE_VACATION';
export const EDIT_VACATION = 'EDIT_VACATION';
export const EDIT_VACATION_FAIL = 'EDIT_VACATION_FAIL';

export const DRAW_CHART_START = 'DRAW_CHART_START';
export const DRAW_CHART_SUCCESS = 'DRAW_CHART_SUCCESS';
export const DRAW_CHART_FAIL = 'DRAW_CHART_FAIL';

export const DELETE_PERSONAL_DATA = 'DELETE_PERSONAL_DATA';

export const FETCH_COLLECTION_START = 'FETCH_COLLECTION_START';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_FAIL = 'FETCH_COLLECTION_FAIL';